[theme]
base = "light"
primaryColor = "#ff0000"  # Vermelho
backgroundColor = "#e0f7fa"  # Branco
secondaryBackgroundColor = "#f5f5f5"  # Um tom claro de cinza para o fundo secundário
textColor = "#000000"  # Preto
